In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyplot
import seaborn as sbn

In [5]:
# 1. Create a null vector of size 10 (★☆☆)

ar = []
for i in range(0, 10):
    ar.append(0)


print(ar)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [3]:
# 2. Create a vector with values ranging from 10 to 49 (★☆☆)

ar = []
for i in range(10, 50):
    ar.append(i)

print(ar)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [14]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

matrix = []
val = 0

for i in range(0, 3):
    row = []
    for j in range(0, 3):
        row.append(val)
        val += 1

    matrix.append(row)

print(matrix)


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [28]:
# 4. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
import numpy as np

matrix = []

for i in range(0, 10):
    row = []
    for j in range(0, 10):
        
        row.append(np.random.random())

    matrix.append(row)

matr = np.array(matrix)
print(matr)

print("min = " + str(matr.min()), "max = " + str(matr.max()))

[[0.37576022 0.31182032 0.22547784 0.7474415  0.1061936  0.59147845
  0.34346771 0.19109138 0.91337599 0.45259487]
 [0.82214529 0.81659165 0.14764339 0.22387938 0.95495456 0.23630054
  0.87327741 0.38747001 0.04739816 0.75910056]
 [0.5907508  0.49396761 0.31440329 0.01876107 0.0108756  0.99675738
  0.81453254 0.86590706 0.65637885 0.73577485]
 [0.31322849 0.12686125 0.79957134 0.313241   0.69566485 0.9994201
  0.92244536 0.70913991 0.31771456 0.09615074]
 [0.50918871 0.46398112 0.19412994 0.77269486 0.10755396 0.63378819
  0.67867817 0.43389319 0.76419119 0.37063209]
 [0.06961882 0.42643909 0.23212287 0.62545988 0.34084738 0.54516658
  0.94384835 0.34384798 0.53876274 0.91200229]
 [0.2420045  0.3592615  0.12551457 0.27716501 0.39853388 0.70638785
  0.49339527 0.12941899 0.37418485 0.75133902]
 [0.27514456 0.19926879 0.96225811 0.53701117 0.31197643 0.81999541
  0.10360923 0.11522713 0.41166165 0.27631641]
 [0.15439844 0.66745695 0.32067253 0.48716282 0.17236279 0.72100803
  0.36733987 

In [104]:
# 5. Create the given matrix: (★☆☆)

matrix = []

for i in range(0, 5):
    row = []
    for j in range(0, 4):
        if i == j:
            row.append(i + 1)
        else:
            row.append(0)

    matrix.append(row)

print(matrix)

[[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4], [0, 0, 0, 0]]


In [19]:
# Run the code below to get the matrix for the tasks from 6 to 10:
np.random.seed(42)

matrix = np.random.uniform(low = 0, high = 100, size = (9, 7))
matrix = np.round(matrix, 0)

print(matrix)

[[37. 95. 73. 60. 16. 16.  6.]
 [87. 60. 71.  2. 97. 83. 21.]
 [18. 18. 30. 52. 43. 29. 61.]
 [14. 29. 37. 46. 79. 20. 51.]
 [59.  5. 61. 17.  7. 95. 97.]
 [81. 30. 10. 68. 44. 12. 50.]
 [ 3. 91. 26. 66. 31. 52. 55.]
 [18. 97. 78. 94. 89. 60. 92.]
 [ 9. 20.  5. 33. 39. 27. 83.]]


In [124]:
# 6. Print the first and the last row with one slice operation  (★☆☆)

print(matrix[0])
print(matrix[-1])

[37. 95. 73. 60. 16. 16.  6.]
[ 9. 20.  5. 33. 39. 27. 83.]


In [12]:
# 7. Print all elements less than 10  (★☆☆)

ar = []

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        if matrix[i][j] < 10.0:
            ar.append(j)

print(ar)

[6, 3, 1, 4, 0, 0, 2]


In [14]:
for i in range(len(matrix)):
    if i % 2 == 0:
        print(matrix[i])

[37. 95. 73. 60. 16. 16.  6.]
[18. 18. 30. 52. 43. 29. 61.]
[59.  5. 61. 17.  7. 95. 97.]
[ 3. 91. 26. 66. 31. 52. 55.]
[ 9. 20.  5. 33. 39. 27. 83.]


In [15]:
for i in range(len(matrix)):
    if i % 2 != 0:
        print(matrix[i])

[87. 60. 71.  2. 97. 83. 21.]
[14. 29. 37. 46. 79. 20. 51.]
[81. 30. 10. 68. 44. 12. 50.]
[18. 97. 78. 94. 89. 60. 92.]


In [17]:
M2 = matrix

[[37. 95. 73. 60. 16. 16.  6.]
 [87. 60. 71.  2. 97. 83. 21.]
 [18. 18. 30. 52. 43. 29. 61.]
 [14. 29. 37. 46. 79. 20. 51.]
 [59.  5. 61. 17.  7. 95. 97.]
 [81. 30. 10. 68. 44. 12. 50.]
 [ 3. 91. 26. 66. 31. 52. 55.]
 [18. 97. 78. 94. 89. 60. 92.]
 [ 9. 20.  5. 33. 39. 27. 83.]]


In [23]:
ar = []

for i in range(len(matrix)):
    sum = 0
    for j in range(len(matrix[i])):
        sum += matrix[i][j]

    ar.append(sum / 7)

print(ar)

[43.285714285714285, 60.142857142857146, 35.857142857142854, 39.42857142857143, 48.714285714285715, 42.142857142857146, 46.285714285714285, 75.42857142857143, 30.857142857142858]


In [25]:
ar = []

for i in range(3):
    row = []
    for j in range(5):
        row.append(5)
    ar.append(row)
print(ar)

[[5, 5, 5, 5, 5], [5, 5, 5, 5, 5], [5, 5, 5, 5, 5]]


In [35]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arr = []
for i in range(2):
    ar = []
    for j in range(3):
        ar.append((arrayOne[i][j] + arrayTwo[i][j]) ** 2)

    arr.append(ar)

print(arr)

[[400, 1521, 1089], [625, 625, 784]]


In [63]:
df = pd.read_csv('/home/sanarip03/Downloads/video_games_sales.csv')
df1 = df.head(5)
print(df1)

                       Name Platform  Year_of_Release         Genre Publisher  \
0                Wii Sports      Wii           2006.0        Sports  Nintendo   
1         Super Mario Bros.      NES           1985.0      Platform  Nintendo   
2            Mario Kart Wii      Wii           2008.0        Racing  Nintendo   
3         Wii Sports Resort      Wii           2009.0        Sports  Nintendo   
4  Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0     41.36     28.96      3.77         8.45         82.53          76.0   
1     29.08      3.58      6.81         0.77         40.24           NaN   
2     15.68     12.76      3.79         3.29         35.52          82.0   
3     15.61     10.93      3.28         2.95         32.77          80.0   
4     11.27      8.89     10.22         1.00         31.37           NaN   

   Critic_Count User_Score  User_Count Developer Rating 

In [ ]:
for col in df.columns:
	print(col)

In [72]:
df = pd.read_csv('/home/sanarip03/Downloads/video_games_sales.csv')
df1 = df.sort_values(by="Year_of_Release", ascending=True)
print(df1.head(5))

                 Name Platform  Year_of_Release     Genre   Publisher  \
262         Asteroids     2600           1980.0   Shooter       Atari   
5360          Freeway     2600           1980.0    Action  Activision   
546   Missile Command     2600           1980.0   Shooter       Atari   
2650           Boxing     2600           1980.0  Fighting  Activision   
4019       Ice Hockey     2600           1980.0    Sports  Activision   

      NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
262       4.00      0.26       0.0         0.05          4.31           NaN   
5360      0.32      0.02       0.0         0.00          0.34           NaN   
546       2.56      0.17       0.0         0.03          2.76           NaN   
2650      0.72      0.04       0.0         0.01          0.77           NaN   
4019      0.46      0.03       0.0         0.01          0.49           NaN   

      Critic_Count User_Score  User_Count Developer Rating  
262            NaN       

In [73]:
mean = df["Year_of_Release"].mean()
print(mean)

2006.4873556231003


In [75]:
df = pd.read_csv('/home/sanarip03/Downloads/video_games_sales.csv')
df1 = df.sort_values(by="Genre", ascending=True)
print(df1.head(5))

                                                  Name Platform  \
15879                                 Reine des Fleurs      PSV   
15736                      Prototype: Biohazard Bundle      PS4   
15735  Katekyoo Hitman Reborn! Kindan no Yami no Delta      PS2   
15734                           Kimikare: New Semester      PSP   
14104            Warhammer: The End Times - Vermintide      PS4   

       Year_of_Release   Genre              Publisher  NA_Sales  EU_Sales  \
15879           2015.0  Action           Idea Factory      0.00      0.00   
15736           2016.0  Action             Activision      0.01      0.00   
15735           2008.0  Action  Marvelous Interactive      0.00      0.00   
15734           2012.0  Action           Idea Factory      0.00      0.00   
14104           2016.0  Action         Games Workshop      0.01      0.02   

       JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  \
15879      0.02         0.00          0.02           NaN    

In [ ]:
df = pd.read_csv('/home/sanarip03/Downloads/video_games_sales.csv')

df1 = df[df["Publisher"] == "Sega"]
print(df1)

In [ ]:
import pandas as pd
df = pd.read_csv('/home/sanarip03/Downloads/video_games_sales.csv')

df_ubisoft_sports = df[(df['Publisher'] == 'Ubisoft') & (df['Genre'] == 'Sports')]
print(df_ubisoft_sports)

In [ ]:
mx = df['EU_Sales'].max()
game_name = df.loc[df['EU_Sales'] == mx, 'Name'].iloc[0]
print(f"{game_name}, {mx}")

In [ ]:
mx = df['Global_Sales'].max()
mn = df['Global_Sales'].min()
diff = mx - mn
print(f"{diff}")